server:
  port: 8081

spring:

  application:
    name: shop-auth

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  datasource:
    url: jdbc:mysql://localhost:3306/shop_auth?serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    database: 0
